.TH KUMLAUNCHER 1 "2026" "kumde 0.8.0" "KumDE Manual"
.SH NAME
kumlauncher \- application launcher for KumDE
.SH SYNOPSIS
.B kumlauncher
.SH DESCRIPTION
kumlauncher is a dmenu-style application launcher. It opens a
layer-shell overlay at the top of the screen listing applications
collected from XDG desktop entries (\fI$XDG_DATA_HOME/applications\fR,
\fI$XDG_DATA_DIRS\fR) and executables on \fB$PATH\fR. Type to filter,
arrow keys or Page Up/Down to navigate, Enter to launch, Escape to
dismiss.
.SH SEE ALSO
.BR kumde (1),
.BR kumde-msg (1)
